"""add memory_facts.is_sensitive

Revision ID: 4d6ae7356da1
Revises: 8553b3bf1bb1
Create Date: 2026-09-17 01:31:17.888256
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d6ae7356da1'
down_revision: Union[str, None] = '8553b3bf1bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'memory_facts',
        sa.Column(
            'is_sensitive',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_facts', 'is_sensitive')
    # ### end Alembic commands ###
