"""initial schema

Revision ID: 8553b3bf1bb1
Revises: 
Create Date: 2026-09-17 00:48:48.230488
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8553b3bf1bb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('style_guide', sa.Text(), nullable=False),
    sa.Column('exemplars_json', sa.Text(), nullable=False),
    sa.Column('safety_categories_json', sa.Text(), nullable=False),
    sa.Column('safety_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('memory_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('conversation_key', sa.String(length=255), nullable=False),
    sa.Column('fact_text', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_facts_conversation_key'), 'memory_facts', ['conversation_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_facts_conversation_key'), table_name='memory_facts')
    op.drop_table('memory_facts')
    op.drop_table('personas')
    # ### end Alembic commands ###
